export const DATASET_VERSION = 10;

const createQuestion = ({id,term,definition,question,options,correct,fillAnswer,answer,fullFillAnswer}) => ({id,term,definition,quiz:{question,options,correct},fillAnswer,answer,fullFillAnswer});

export const chapters = [
  {
    id: 110025,
    title: "Triết học Mác-Lênin: Câu hỏi ôn tập",
    description: "20 câu hỏi ôn tập tổng hợp về triết học Mác-Lênin.",
    icon: "📚",
    questions: [
      createQuestion({
        id: 1,
        term: "Nguồn gốc xã hội của triết học",
        definition: "Triết học ra đời gắn với sự phân công lao động trí óc-chân tay, sự ra đời giai cấp và nhà nước trong chế độ chiếm hữu nô lệ.",
        question: "Nguồn gốc xã hội của triết học gắn liền với điều kiện nào sau đây?",
        options: ["Xã hội cộng sản nguyên thủy với lao động tập thể","Sự phân công lao động trí óc-chân tay, sự ra đời giai cấp và nhà nước trong chế độ chiếm hữu nô lệ","Sự phát triển của tôn giáo nguyên thủy và huyền thoại","Sự hình thành các khoa học chuyên ngành độc lập ở Hy Lạp cổ đại"],
        correct: 1,
        fillAnswer: "Nguồn gốc xã hội của triết học gắn với ______ và sự ra đời nhà nước.",
        answer: "sự phân công lao động trí óc-chân tay",
        fullFillAnswer: "Triết học ra đời khi xã hội có sự phân công lao động trí óc-chân tay, giai cấp và nhà nước hình thành.",
      }),
      createQuestion({
        id: 2,
        term: "Câu khẳng định của C.Mác về triết học",
        definition: "C.Mác nhấn mạnh triết học có nguồn gốc xã hội và thực tiễn, không tách rời thế giới.",
        question: "Câu 'Triết học không treo lơ lửng ở ngoài thế giới' được trích từ ai và nhấn mạnh điều gì?",
        options: ["Kant – nhấn mạnh tính tiên nghiệm của triết học","C. Mác – nhấn mạnh nguồn gốc xã hội và thực tiễn của triết học","Hegel – nhấn mạnh tính tuyệt đối của tinh thần","Aristotle – nhấn mạnh vai trò khoa học của các khoa học"],
        correct: 1,
        fillAnswer: "Câu trích dẫn về triết học gắn với thế giới thuộc về ______.",
        answer: "C. Mác",
        fullFillAnswer: "C. Mác dùng câu đó để nhấn mạnh nguồn gốc xã hội và thực tiễn của triết học.",
      }),
      createQuestion({
        id: 3,
        term: "Triết học khác huyền thoại và tôn giáo",
        definition: "Triết học khác huyền thoại và tôn giáo nguyên thủy ở tính hệ thống, lôgích, trừu tượng và dựa trên lý tính.",
        question: "Điểm khác biệt cơ bản giữa triết học với tư duy huyền thoại và tôn giáo nguyên thủy nằm ở?",
        options: ["Việc sử dụng ngôn ngữ và biểu tượng","Tính hệ thống, lôgích, trừu tượng và dựa trên lý tính thay vì niềm tin và hoang tưởng","Phạm vi bao quát thế giới","Vai trò định hướng hành vi xã hội"],
        correct: 1,
        fillAnswer: "Triết học khác tôn giáo nguyên thủy ở tính ______ và dựa trên lý tính.",
        answer: "hệ thống, lôgích, trừu tượng",
        fullFillAnswer: "Triết học dựa trên lý tính và tư duy trừu tượng, có hệ thống; khác với huyền thoại và tôn giáo dựa trên niềm tin.",
      }),
      createQuestion({
        id: 4,
        term: "Đối tượng của triết học Mác-Lênin",
        definition: "Triết học Mác-Lênin xác định đối tượng là hệ thống quan điểm lý luận chung nhất về thế giới và quy luật vận động chung nhất.",
        question: "Triết học Mác-Lênin xác định đối tượng của triết học là gì?",
        options: ["Khoa học của các khoa học bao quát tất cả tri thức cụ thể","Hệ thống quan điểm lý luận chung nhất về thế giới, con người và quy luật vận động của tự nhiên, xã hội, tư duy","Chỉ tập trung vào phân tích ngôn ngữ và hiện tượng tinh thần","Nghiên cứu các vấn đề đạo đức và nhân sinh quan thuần túy"],
        correct: 1,
        fillAnswer: "Đối tượng triết học Mác-Lênin là hệ thống quan điểm ______ về thế giới và con người.",
        answer: "lý luận chung nhất",
        fullFillAnswer: "Triết học Mác-Lênin nghiên cứu những quy luật chung nhất của tự nhiên, xã hội và tư duy.",
      }),
      createQuestion({
        id: 5,
        term: "Khái niệm thế giới quan của Kant",
        definition: "Kant lần đầu dùng khái niệm thế giới quan theo nghĩa hiện đại trong tác phẩm Phê phán năng lực phán đoán.",
        question: "Khái niệm 'thế giới quan' theo nghĩa hiện đại lần đầu được Kant sử dụng trong tác phẩm nào?",
        options: ["Phê phán lý tính thuần túy","Phê phán năng lực phán đoán (Kritik der Urteilskraft)","Hiện tượng học tinh thần","Biện chứng của tự nhiên"],
        correct: 1,
        fillAnswer: "Kant lần đầu dùng khái niệm thế giới quan trong tác phẩm ______.",
        answer: "Phê phán năng lực phán đoán",
        fullFillAnswer: "Khái niệm thế giới quan theo nghĩa hiện đại lần đầu được Kant dùng trong Phê phán năng lực phán đoán.",
      }),
      createQuestion({
        id: 6,
        term: "Triết học là hạt nhân lý luận của thế giới quan",
        definition: "Triết học là hạt nhân lý luận của thế giới quan vì là thành phần cốt lõi chi phối các hình thức thế giới quan khác.",
        question: "Triết học được coi là 'hạt nhân lý luận của thế giới quan' vì?",
        options: ["Nó là hình thức thế giới quan duy nhất có giá trị","Nó là thành phần cốt lõi chi phối các hình thức thế giới quan khác và cung cấp hệ thống quan điểm lý luận chung nhất","Nó chỉ tồn tại trong giới trí thức","Nó thay thế hoàn toàn tôn giáo và khoa học"],
        correct: 1,
        fillAnswer: "Triết học là hạt nhân lý luận vì là ______ chi phối các hình thức thế giới quan khác.",
        answer: "thành phần cốt lõi",
        fullFillAnswer: "Triết học là hạt nhân lý luận của thế giới quan vì cung cấp hệ thống quan điểm chung nhất, chi phối các hình thức thế giới quan khác.",
      }),
      createQuestion({
        id: 7,
        term: "Mặt thứ nhất vấn đề cơ bản của triết học",
        definition: "Theo Ăngghen, mặt thứ nhất là mối quan hệ giữa tồn tại và tư duy, vật chất và ý thức – cái nào có trước và quyết định cái nào.",
        question: "Mặt thứ nhất của 'vấn đề cơ bản của triết học' (theo Ăngghen) là gì?",
        options: ["Khả năng nhận thức thế giới của con người","Mối quan hệ giữa tồn tại và tư duy, giữa vật chất và ý thức – cái nào có trước và quyết định cái nào","Mối quan hệ giữa con người và xã hội","Bản chất của mâu thuẫn biện chứng"],
        correct: 1,
        fillAnswer: "Mặt thứ nhất vấn đề cơ bản là mối quan hệ giữa ______ – cái nào có trước.",
        answer: "vật chất và ý thức",
        fullFillAnswer: "Theo Ăngghen, mặt thứ nhất là vật chất và ý thức cái nào có trước và quyết định cái nào.",
      }),
      createQuestion({
        id: 8,
        term: "CNDV biện chứng khác CNDV siêu hình",
        definition: "CNDV biện chứng xem xét thế giới trong vận động, phát triển, liên hệ phổ biến và mâu thuẫn nội tại.",
        question: "Chủ nghĩa duy vật biện chứng khác chủ nghĩa duy vật siêu hình ở điểm nào?",
        options: ["Thừa nhận vai trò của tinh thần trong sự sáng tạo thế giới","Xem xét thế giới trong sự vận động, phát triển, liên hệ phổ biến và mâu thuẫn nội tại","Chỉ dựa vào kinh nghiệm cảm tính trực quan","Phủ nhận hoàn toàn vai trò của thực tiễn"],
        correct: 1,
        fillAnswer: "CNDV biện chứng xem xét thế giới trong ______ và mâu thuẫn nội tại.",
        answer: "vận động, phát triển, liên hệ phổ biến",
        fullFillAnswer: "CNDV biện chứng khác siêu hình ở chỗ xem xét thế giới trong vận động, phát triển và mâu thuẫn nội tại.",
      }),
      createQuestion({
        id: 9,
        term: "Chủ nghĩa duy tâm chủ quan",
        definition: "CNDT chủ quan điển hình thừa nhận mọi sự vật chỉ là phức hợp của cảm giác của chủ thể.",
        question: "Chủ nghĩa duy tâm chủ quan điển hình thừa nhận điều gì?",
        options: ["Tinh thần khách quan độc lập với con người là bản nguyên","Mọi sự vật chỉ là phức hợp của cảm giác của chủ thể","Vật chất và tinh thần là hai bản nguyên song song","Ý niệm tuyệt đối là nguồn gốc của thế giới"],
        correct: 1,
        fillAnswer: "CNDT chủ quan thừa nhận sự vật chỉ là phức hợp của ______ của chủ thể.",
        answer: "cảm giác",
        fullFillAnswer: "CNDT chủ quan (Berkeley) cho rằng mọi sự vật chỉ là phức hợp cảm giác của chủ thể nhận thức.",
      }),
      createQuestion({
        id: 10,
        term: "Thuyết bất khả tri của Kant",
        definition: "Thuyết bất khả tri của Kant dựa trên khái niệm vật tự nó – thứ con người không thể nhận thức được.",
        question: "Thuyết bất khả tri (Agnosticism) của Kant chủ yếu dựa trên khái niệm nào?",
        options: ["Biện chứng duy tâm","Vật tự nó (Ding an sich)","Phép biện chứng tự phát","Nhất nguyên luận duy vật"],
        correct: 1,
        fillAnswer: "Thuyết bất khả tri của Kant dựa trên khái niệm ______.",
        answer: "vật tự nó (Ding an sich)",
        fullFillAnswer: "Kant cho rằng con người chỉ nhận thức được hiện tượng, còn vật tự nó thì không thể biết được.",
      }),
      createQuestion({
        id: 11,
        term: "Phương pháp siêu hình",
        definition: "Phương pháp siêu hình coi nguyên nhân biến đổi nằm bên ngoài và chỉ thừa nhận biến đổi về lượng.",
        question: "Phương pháp siêu hình coi nguyên nhân biến đổi chủ yếu nằm ở đâu?",
        options: ["Mâu thuẫn nội tại của sự vật","Bên ngoài đối tượng, và chỉ thừa nhận biến đổi về lượng","Sự phát triển từ thấp đến cao theo quy luật phủ định của phủ định","Liên hệ phổ biến giữa các sự vật"],
        correct: 1,
        fillAnswer: "Phương pháp siêu hình coi nguyên nhân biến đổi nằm ______ và chỉ thừa nhận biến đổi về lượng.",
        answer: "bên ngoài đối tượng",
        fullFillAnswer: "Phương pháp siêu hình xem nguyên nhân biến đổi là bên ngoài, không thấy bước nhảy về chất.",
      }),
      createQuestion({
        id: 12,
        term: "Phép BC duy vật khác phép BC duy tâm Hegel",
        definition: "Phép BC duy vật gạt bỏ tính thần bí, tư biện của Hegel, thống nhất duy vật với biện chứng.",
        question: "Phép biện chứng duy vật của Mác-Ăngghen khác phép biện chứng duy tâm của Hegel ở chỗ?",
        options: ["Bắt nguồn từ tinh thần và kết thúc ở tinh thần","Gạt bỏ tính thần bí, tư biện, thống nhất chủ nghĩa duy vật với phép biện chứng","Chỉ dừng ở mức trực quan tự phát","Phủ nhận vai trò của thực tiễn"],
        correct: 1,
        fillAnswer: "Phép BC duy vật gạt bỏ tính ______ của Hegel, thống nhất duy vật với biện chứng.",
        answer: "thần bí, tư biện",
        fullFillAnswer: "Mác-Ăngghen kế thừa hạt nhân hợp lý của Hegel nhưng gạt bỏ vỏ thần bí, thống nhất duy vật và biện chứng.",
      }),
      createQuestion({
        id: 13,
        term: "Điều kiện KT-XH ra đời triết học Mác",
        definition: "Điều kiện quan trọng nhất là cách mạng công nghiệp phát triển mạnh và mâu thuẫn tư sản-vô sản gay gắt.",
        question: "Điều kiện kinh tế-xã hội quan trọng nhất dẫn đến sự ra đời triết học Mác là?",
        options: ["Sự suy tàn của phong kiến châu Âu","Sự phát triển mạnh mẽ của lực lượng sản xuất trong cách mạng công nghiệp và mâu thuẫn giai cấp tư sản-vô sản gay gắt","Ảnh hưởng của triết học cổ điển Đức","Sự ra đời của các khoa học thực nghiệm"],
        correct: 1,
        fillAnswer: "Điều kiện KT-XH quan trọng nhất là cách mạng công nghiệp và mâu thuẫn ______ gay gắt.",
        answer: "tư sản-vô sản",
        fullFillAnswer: "Cách mạng công nghiệp và mâu thuẫn tư sản-vô sản gay gắt là điều kiện KT-XH quan trọng nhất sinh ra triết học Mác.",
      }),
      createQuestion({
        id: 14,
        term: "Trình độ xã hội để triết học ra đời",
        definition: "Triết học chỉ ra đời khi có phân công lao động trí óc-chân tay, giai cấp phân hóa, nhà nước ra đời.",
        question: "Triết học chỉ ra đời khi xã hội đạt đến trình độ nào?",
        options: ["Lao động tập thể không phân công","Phân công lao động trí óc-chân tay, giai cấp phân hóa, nhà nước ra đời, của cải dư thừa và tư hữu được luật định","Chỉ có tôn giáo nguyên thủy","Các khoa học chuyên ngành đã hoàn toàn độc lập"],
        correct: 1,
        fillAnswer: "Triết học ra đời khi có phân công lao động ______, giai cấp phân hóa và nhà nước ra đời.",
        answer: "trí óc-chân tay",
        fullFillAnswer: "Triết học chỉ ra đời khi xã hội phân hóa giai cấp, nhà nước xuất hiện và lao động trí óc tách khỏi lao động chân tay.",
      }),
      createQuestion({
        id: 15,
        term: "Thế giới quan triết học khác thế giới quan tôn giáo",
        definition: "Triết học dựa trên lý tính, lôgích và tri thức khoa học; tôn giáo dựa trên tín điều và mặc khải.",
        question: "Điểm khác biệt quan trọng giữa thế giới quan triết học với thế giới quan tôn giáo là?",
        options: ["Đều dựa hoàn toàn vào niềm tin","Triết học dựa trên lý tính, lôgích và tri thức khoa học; tôn giáo dựa trên tín điều và mặc khải","Cùng phủ nhận vai trò của khoa học","Đều là sản phẩm của giai cấp thống trị"],
        correct: 1,
        fillAnswer: "Triết học dựa trên ______ trong khi tôn giáo dựa trên tín điều và mặc khải.",
        answer: "lý tính, lôgích và tri thức khoa học",
        fullFillAnswer: "TGQ triết học dựa trên lý tính và tri thức khoa học; TGQ tôn giáo dựa trên niềm tin và mặc khải.",
      }),
      createQuestion({
        id: 16,
        term: "Nhị nguyên luận",
        definition: "Nhị nguyên luận (Descartes) cuối cùng thuộc lập trường duy tâm vì không giải quyết triệt để vấn đề cơ bản.",
        question: "Nhị nguyên luận (ví dụ Descartes) cuối cùng thuộc về lập trường nào?",
        options: ["Duy vật triệt để","Duy tâm (vì không giải quyết triệt để vấn đề cơ bản của triết học)","Bất khả tri","Siêu hình"],
        correct: 1,
        fillAnswer: "Nhị nguyên luận thuộc lập trường ______ vì không giải quyết triệt để vấn đề cơ bản.",
        answer: "duy tâm",
        fullFillAnswer: "Nhị nguyên luận không giải quyết được vấn đề cơ bản của triết học nên cuối cùng rơi vào lập trường duy tâm.",
      }),
      createQuestion({
        id: 17,
        term: "Ăngghen phê phán Kant về vật tự nó",
        definition: "Ăngghen lập luận: nếu con người tạo ra hiện tượng và làm nó phục vụ mục đích, thì vật tự nó không còn tồn tại.",
        question: "Ăngghen phê phán Kant về 'vật tự nó' bằng lập luận nào?",
        options: ["Con người không thể vượt qua giới hạn kinh nghiệm","Nếu con người tự tạo ra hiện tượng từ điều kiện của nó và làm cho nó phục vụ mục đích, thì vật tự nó không còn tồn tại","Vật tự nó chính là tinh thần tuyệt đối","Nhận thức chỉ là ảo tưởng"],
        correct: 1,
        fillAnswer: "Ăngghen lập luận: nếu con người tạo ra hiện tượng phục vụ mục đích thì ______ không còn tồn tại.",
        answer: "vật tự nó",
        fullFillAnswer: "Ăngghen chứng minh thực tiễn bác bỏ bất khả tri của Kant: con người có thể nhận thức và cải tạo thế giới.",
      }),
      createQuestion({
        id: 18,
        term: "Triết học Hy Lạp cổ đại",
        definition: "Triết học Hy Lạp cổ đại được Ăngghen đánh giá cao vì có mầm mống hầu hết các thế giới quan sau này.",
        question: "Triết học Hy Lạp cổ đại được Ăngghen đánh giá cao vì?",
        options: ["Đã giải quyết triệt để vấn đề cơ bản của triết học","Có mầm mống hầu hết các thế giới quan sau này","Đã tách hoàn toàn khỏi tôn giáo","Chỉ tập trung vào logic hình thức"],
        correct: 1,
        fillAnswer: "Triết học Hy Lạp cổ đại được đánh giá cao vì có ______ hầu hết các thế giới quan sau này.",
        answer: "mầm mống",
        fullFillAnswer: "Ăngghen nhận xét triết học Hy Lạp cổ đại là hình thức sơ khai có mầm mống hầu hết các thế giới quan về sau.",
      }),
      createQuestion({
        id: 19,
        term: "CNDV siêu hình đạt đỉnh cao",
        definition: "CNDV siêu hình đạt đỉnh cao thế kỷ XVII-XVIII dưới ảnh hưởng của cơ học cổ điển Newton.",
        question: "Trong lịch sử, CNDV siêu hình đạt đỉnh cao ở thế kỷ nào và chịu ảnh hưởng mạnh của gì?",
        options: ["Thế kỷ XIX – ảnh hưởng của Hegel","Thế kỷ XVII-XVIII – ảnh hưởng của cơ học cổ điển","Thời cổ đại – ảnh hưởng của tôn giáo","Thế kỷ XX – ảnh hưởng của vật lý lượng tử"],
        correct: 1,
        fillAnswer: "CNDV siêu hình đạt đỉnh cao thế kỷ XVII-XVIII dưới ảnh hưởng của ______.",
        answer: "cơ học cổ điển",
        fullFillAnswer: "Cơ học cổ điển Newton phát triển mạnh thế kỷ XVII-XVIII đã chi phối và định hình phương pháp siêu hình.",
      }),
      createQuestion({
        id: 20,
        term: "Vai trò của triết học Mác-Lênin",
        definition: "Triết học Mác-Lênin là thế giới quan khoa học, phương pháp luận cách mạng, cơ sở lý luận cho đường lối của Đảng.",
        question: "Vai trò của triết học Mác-Lênin trong đời sống xã hội theo giáo trình là?",
        options: ["Chỉ mang tính học thuật","Là thế giới quan khoa học, phương pháp luận cách mạng, cơ sở lý luận cho đường lối của Đảng và đấu tranh tư tưởng","Thay thế hoàn toàn các khoa học cụ thể","Chỉ phục vụ cho giai cấp vô sản ở phương Tây"],
        correct: 1,
        fillAnswer: "Triết học Mác-Lênin là thế giới quan khoa học và ______ cách mạng.",
        answer: "phương pháp luận",
        fullFillAnswer: "Triết học Mác-Lênin là TGQ khoa học, phương pháp luận cách mạng và cơ sở lý luận cho đường lối của Đảng.",
      }),
    ],
  },
];
